#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the AZURE network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 *
 * Seeds:
 *   64.188.22.190:29825
 *   194.135.93.22:29825
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x40,0xbc,0x16,0xbe,0x74,0x81,
    0x01,0x04,0xc2,0x87,0x5d,0x16,0x74,0x81,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
